[libiconv] Various refactors of existing code
chef-base-plans/libiconv pull request #2
Opened 2020-06-22 16:43 UTC by MindNumbing

Add inspec.lock to .gitignore
Update README.md to the latest library format
Added plan_name to attributes.yml file
Update control description, added stderr check and prescriptive version check
Updated inspec.yml to latest format

Signed-off-by: Steven Marshall <SMarshall@chef.io>

2020-06-24 11:29 UTC, gavindidrichsen requested changes
One small change, otherwise looks good!

2020-06-24 11:29 UTC, gavindidrichsen commented on README.md
>  Binary package
This should be changed to "Library package".

2020-06-26 13:26 UTC, skpaterson approved these changes
Thanks @MindNumbing

2020-07-06 08:48 UTC, gavindidrichsen approved these changes

2020-07-06 08:48 UTC, merged